#!/bin/sh
# Build the WebAssembly core of the web interface.
#
# Needs clang and wasm-ld (LLVM), nothing else: no Emscripten, no C
# library. Produces ../emu-wasm.js, which holds the WebAssembly module as
# base64, so that index.html also works when opened straight from disk.
set -e
cd "$(dirname "$0")"
SRC=../../emu6502/src

clang --target=wasm32 -std=c11 -O2 -Wall -Wextra \
      -mbulk-memory -nostdlib -ffreestanding \
      -Ishim -I"$SRC" \
      -Wl,--no-entry -Wl,--strip-all -Wl,-z,stack-size=65536 \
      -o emu.wasm \
      emu_wasm.c "$SRC/cpu.c" "$SRC/opcodes.c" "$SRC/sbc.c" \
      "$SRC/acia.c" "$SRC/via.c"

{
    printf '// Generated by web/wasm/build.sh - do not edit.\n'
    printf 'window.EMU_WASM_BASE64 = "'
    base64 < emu.wasm | tr -d '\n'
    printf '";\n'
} > ../emu-wasm.js

rm -f emu.wasm
ls -l ../emu-wasm.js
